### ISSUE TITLE
BB-2: GraphBLAS typecasting is undefined

### ISSUE THREAD

**Issue by mcmillan03** [GraphBLAS/graphblas-api-c#1]
The GraphBLAS API states that typecasting follows the rules of ANSI C. Yet C leaves some typecasting undefined (float or double to integer, in particular). SuiteSparse:GraphBLAS provides a precise definition for all typecasting as an extension to the spec.

Does GraphBLAS need to adopt more precise casting language, should it be implementation-dependent, or implementation-defined?

**Comment by tgmattso** [comment]
NO.  I hope we don't say we follow ANSI C casting.  We should say we use the casting of the C compiler used to build the library.     That leaves nothing undefined ... or rather it passes the buck.

I do not want to fully define casting details since it would cause us to add lots of extra work on the implementor to check all casting options on their own before going into the guts of their code.  That adds a great deal of pain for the implementor.

**Comment by DrTimothyAldenDavis** [comment]
Typecasting a float that is outside the range of an int leads to all kinds of undefined nastiness, and ANSI C11 gives an undefined result, and the result even depends on the compiler optimization level.  This breaks all my tests.

```
$ cat nasty.c
#include <stdio.h>
int main (void)
{
    float x = 1e40 ;
    int i = x ;
    printf ("i %d\n", i) ;
}
$ cc nasty.c ; ./a.out
i -2147483648
$ cc -O2 nasty.c ; ./a.out
i 2147483647
```

However, if you want the spec to be silent on this, I can still use my own typecasting from floating point to integers.

**Comment by DrTimothyAldenDavis** [comment]
The spec does state that ANSI C11 typecasting is followed.

**Comment by DrTimothyAldenDavis** [comment]
The spec states the following for typecasting, emphasis added.  "The C language" would mean "ANSI C11" since that is the language stated earlier in the spec for the _Generic keyword.

> domain compatible: Two domains for which values from one domain can be cast to values in
> the other domain **_as per the rules of the C language_**. In particular, domains from Table 3.2
> are all compatible with each other, and a domain from a user-defined type is only compatible
> with itself. If any domain compatibility rule above is violated, execution of the GraphBLAS
> method ends and the GrB_DOMAIN_MISMATCH error is returned.

**Comment by mcmillan03** [comment]
If we state ANSI C11, does that satisfy this issue.  Or is more language regarding the language's undefined behaviour need to be added?

**Comment by DrTimothyAldenDavis** [comment]
The spec already states ANSI C11, at least implicitly in the phrase "as per the rules of the C language".  I doubt that typecasting changed from C99 to C11.

The only issue is that ANSI C11 leaves some typecasting undefined or implementation-defined.  In particular, casting from an unsigned integer to a signed integer result, if the value can't be represented in the result, is "implementation-defined".  Casting from a floating point to an integer results in "undefined" results if the value can't be represented, after discarding the fractional part.

I'm OK if you want to close this issue, and pass the buck with "per the rules of the C language".  Maybe just add the clarification "per the rules of the ANSI C11 language" if you want to be precise.

**Comment by DrTimothyAldenDavis** [comment]
We can close this comment.  The spec is fine as-is.  It states that typecasting is defined by the C language, which is sufficient.
