### ISSUE TITLE
BB-22: Extend boolean binary ops to T x T --> T

### ISSUE THREAD

**Issue by mcmillan03** [GraphBLAS/graphblas-api-c#10]
E.g., Suitesparse's `GxB_LAND_UINT32`

**Comment by tgmattso** [comment]
I need some elaboration here.  What does this mean?

I feel this interacts with the discussion about defining a context.       GrB_init() creates a new context and GrB_finalize() destroys it.   We can then have multiple (even nested) contexts.  Is this what you mean?

**Comment by DrTimothyAldenDavis** [comment]
This has nothing to do with GrB_init and GrB_finalize.

GxB_LAND_UINT32 computes the following: z = (uint32) ((x != 0) && (y != 0)), so its input types are both uint32, and its output type is also uint32.

**Comment by DrTimothyAldenDavis** [comment]
I think this issue can be closed.  I thought it was important to add these operators when I first wrote SuiteSparse:GraphBLAS, but in retrospect they aren't really needed.
