### ISSUE TITLE
BB-32: Create user-defined objects at compile-time

### ISSUE THREAD

**Issue by mcmillan03** [GraphBLAS/graphblas-api-c#18]
The GraphBLAS C API has no mechanism for constructing user-defined objects when GraphBLAS is compiled. Consider Suitesparse 'GxB_*_define' macros.

'GxB_Type_define'  define a 'GrB_Type' at compile-time 
'GxB_UnaryOp_define'  define a 'GrB_UnaryOp' at compile-time 
'GxB_BinaryOp_define'  define a 'GrB_BinaryOp' at compile-time 
'GxB_Monoid_define'  define a 'GrB_Monoid' at compile-time 
'GxB_Semiring_define'  define a 'GrB_Semiring' at compile-time

**Comment by tgmattso** [comment]
We have to be careful not to reinvent C++ inside C.   It's OK to live within the limits presented by the host language.

**Comment by DrTimothyAldenDavis** [comment]
We should close this issue.  I don't support this anymore since it was very difficult to do.  I have a better approach, to do this with a JIT at runtime.
