### ISSUE TITLE
GrB_Matrix_select:  type of T matrix is wrong

### ISSUE THREAD

**Issue by DrTimothyAldenDavis** [GraphBLAS/graphblas-api-c#38]
For GrB_Vector_select, the intermediate vector t is in the same domain as the input vector u, which is correct.

For GrB_Matrix_select, the intermediate matrix T is said to be in the domain of the output of the operator, which is incorrect.  The domain of T should be the same as the domain of the input matrix A.

See line 6670 of the PDF, as of Sept 10 at least.

**Comment by mcmillan03** [comment]
Corrected and pushed (including a typo in DIMENSION_MISMATCH as well).
