### ISSUE TITLE
BB-7: Query global execution mode

### ISSUE THREAD

**Issue by mcmillan03** [GraphBLAS/graphblas-api-c#4]
To query the mode, for example (from Suitesparse:GraphBLAS):

```
GrB_mode mode ;
GxB_get (GxB_MODE, &mode) ;
```

**Comment by tgmattso** [comment]
Yes.   Full introspection is needed.   For every object defined in GraphBLAS and every mode, you can query its value (a GrB_get())

**Comment by manoj63** [comment]
Seems a reasonable philosophy.  Anything that can be set by an application should be query-able also, at least for debugging.
