### ISSUE TITLE
GRB_VERSION and GRB_SUBVERSION

### ISSUE THREAD

**Issue by DrTimothyAldenDavis** [GraphBLAS/graphblas-api-c#43]
> [Scott: Where should the macros be specified?]

In the GraphBLAS.h created in the particular implementation.  That's where I define them already, and I don't see any other place that would be suitable.

**Comment by mcmillan03** [comment]
That is a comment regarding where in the spec the definitions should appear.  Is it only with the method or should it be included in Chapter 3 with all of the other code definitions.

**Comment by DrTimothyAldenDavis** [comment]
Got it.  I misunderstood the comment.
