### ISSUE TITLE
Remove deprecated GrB_SCMP

### ISSUE THREAD

**Issue by mcmillan03** [GraphBLAS/graphblas-api-c#51]
GrB_SCMP has been replaced with GrB_COMP and was deprecated with 1.3 release.  Is v2.0 a good time to remove it from the spec.

**Comment by DrTimothyAldenDavis** [comment]
Just removed GrB_SCMP from my pre-release, v6.0.0.alpha13, https://github.com/DrTimothyAldenDavis/GraphBLAS/releases/tag/v6.0.0.alpha13 .

**Comment by mcmillan03** [comment]
Removed from Table 3.11
