### ISSUE TITLE
New functions have no non-polymorphic names

### ISSUE THREAD

**Issue by DrTimothyAldenDavis** [GraphBLAS/graphblas-api-c#52]
GrB_reduce, when reducing a matrix or vector to a GrB_Scalar using a GrB_BinaryOp (ack!) has no non-polymorphic name.  All there is in Table 5.11 are these 2 functions with GrB_Scalars:

```
GrB_Vector_reduce_Scalar (GrB_Scalar, ..., GrB_Vector, ... )
GrB_Matrix_reduce_Scalar (GrB_Scalar, ..., GrB_Matrix, ... )
```

which I assume are the monoid variants:

```
GrB_Vector_reduce_Scalar (GrB_Scalar s, GrB_BinaryOp accum, GrB_Monoid mon, GrB_Vector u, GrB_Descriptor d)
GrB_Matrix_reduce_Scalar (GrB_Scalar s, GrB_BinaryOp accum, GrB_Monoid mon, GrB_Matrix A, GrB_Descriptor d)
```

I prefer that you simply not add the functions that do reduction via GrB_BinaryOps at all.  That is, I ask that you simply delete lines 6937 to 6942 of the spec, and only refer to the monoid in line 6950.
  
But if you really insist on adding them, I need at least a name of a stub I can use to return GrB_NOT_IMPLEMENTED for those 2 methods.  Otherwise it's a compile time error to try to pass in a binary op, since there's no name to use for these functions in the _Generic switch.

These nameless beasts are a problem anyway ... I suggest you just delete them.  No one will miss them.  I also suggest deprecating GrB_reduce matrix to vector using a binary op, which is also a problem and not needed; a monoid works best for all reductions.

**Comment by tgmattso** [comment]
commenting on Tim's comment at the top of this chain ...

Tim wrote:

      "I need at least a name of a stub I can use to return GrB_NOT_IMPLEMENTED for those 2 methods."

This is an interesting point.  In the draft 2.0 spec where we first mentioned GrB_NOT_IMPLEMENTED we left it wide open as to when this could be used.  We wanted to forbid the situation where someone created a library of stubs that did nothing but return GrB_NOT_IMPLEMENTED and then called that a conformant implementation.   Your comment above makes me think I need to go back and work on the new text some more.

For each method defined by the GraphBLAS spec, there are combinations of parameters that may not be supported (such as reduction with a binary operator) but you can't call an implementation conformant if EVERY set of parameters is not supported.  In other words, for a conformant specification, you MUST have at least one function signature for EVERY function supported.   

But as Tim's comment above suggests, this is not the case for the nonpolymorphic interface.  Indeed, there will be cases from that list that are not implemented.   I need to modify the text on GrB_not_implemented to make this clear.

**Comment by DrTimothyAldenDavis** [comment]
GrB_NOT_IMPLEMENTED is another issue, see #53

**Comment by joseemoreira** [comment]
I will edit the nonpolymorphic names.

**Comment by mcmillan03** [comment]
Assign to Jose to address.

**Comment by joseemoreira** [comment]
I added the missing nonpolymorphic names. I also changed the font size in the tables to "scriptsize", since they were not fitting, even in landscape mode.

I will change the red text to black after reviewing the names one more time.

**Comment by joseemoreira** [comment]
Finished reviewing nonpolymorphic names.
