### ISSUE TITLE
"conformant" library not well defined

### ISSUE THREAD

**Issue by DrTimothyAldenDavis** [GraphBLAS/graphblas-api-c#53]
"conformant" is not well defined.  The draft spec states:

> An implementation of the GraphBLAS C API
> may still call itself “conformant” to this specification if the following conditions hold.
> 1. Every method defined in the GraphBLAS specification is supported for at least one combination of input parameters.
> 2. This situation must be documented as an implementation defined feature of the implementation of the GraphBLAS.
> 3. This situation is caught as an API error (section 2.6) and the parameter GrB_NOT_IMPLEMENTED
> is returned by the associated method call.

Item (1) is vague.  Suppose I wrote a GraphBLAS library that required all Mask inputs to be NULL, and all accum operator inputs to be NULL, and all descriptors to be NULL.  Each operation and method would be supported for many combinations of parameters (just no Mask matrix, no accum operator, no GrB_DESC_T0, etc).  Then I could call the library conformant, as long as I document it and properly return GrB_NOT_IMPLEMENTED.

**Comment by tgmattso** [comment]
OK.  Help me out here.   I don't want to put a number ... X% of functionality must be supported on every method.    I want to give implementors flexibility they need to support a diverse range of platforms.  But I don't want people to get away with weird stunt implementations that abuse the term "conformant".     I could say "the majority of the possible function signatures must be supported" ... but that is the same as saying X=51.    What wording do you suggest?
