### ISSUE TITLE
domain compatible casting?

### ISSUE THREAD

**Issue by tgmattso** [GraphBLAS/graphblas-api-c#55]
I don't understand the point of the red text on line 564.  What do you mean by "domain compatible casting?

**Comment by DrTimothyAldenDavis** [comment]
That refers to lines 529 to 533:

> • domain compatible: Two domains for which values from one domain can be cast to values in
> the other domain as per the rules of the C language. In particular, domains from Table 3.2
> are all compatible with each other, and a domain from a user-defined type is only compatible
> with itself. If any domain compatibility rule above is violated, execution of the GraphBLAS
> method ends and the GrB_DOMAIN_MISMATCH error is returned.

**Comment by mcmillan03** [comment]
Red text needs review to answer the questions "Does this text belong in this section?" and (always) "Is the statement clear and correct?".   yes, the italics refers to a glossary term that Tim D. points out.

**Comment by joseemoreira** [comment]
No change.
