### ISSUE TITLE
Two paragraphs don't make sense 

### ISSUE THREAD

**Issue by tgmattso** [GraphBLAS/graphblas-api-c#56]
Look at the paragraph from lines 597 to 603.  Compare it to the paragraph on line 604.  We need to merge these ... which will mean deleting most of that second paragraph

**Comment by mcmillan03** [comment]
Yes they need to be merged.  Looks like I lost a train of thought and did not get back to it.  The contribution of the second paragraph are the other types of constructor methods: dup, diag, import, deserialize.

**Comment by joseemoreira** [comment]
Made small change to first paragraph and dropped the second.
