### ISSUE TITLE
question regarding D(C) being compatible with Dout(op)

### ISSUE THREAD

**Issue by DrTimothyAldenDavis** [GraphBLAS/graphblas-api-c#59]
on line 2925 the draft states:

> 4. D(C) must be compatible with D out (op) of the semiring. [Scott: SHOULD THIS BE QUAL-
> IFIED: if accum is GrB_NULL? Here and globally?]

This should not be qualified.  If C(i,j) does not exist, but T(i,j) does, then the assignment C(i,j) = T(i,j) is made, bypassing the accumulator.  As a result, when the accum is not NULL, D(C) must still be compatible with Dout(op), which is the type of T in this case.  Line 2925 should be unchanged and you can delete the pending question.

**Comment by mcmillan03** [comment]
Comment removed.
