### ISSUE TITLE
BB-14: Query size of scalar described by `GrB_Type`

### ISSUE THREAD

**Issue by mcmillan03** [GraphBLAS/graphblas-api-c#6]
```
size_t GxB_Type_size(GrB_Type obj);
```
returns the size of a type

**Comment by tgmattso** [comment]
I want to query the full definition of the type ... not just the size

**Comment by DrTimothyAldenDavis** [comment]
Yes, that should be another function however.

**Comment by manoj63** [comment]
Two reasons to do this:
1) Serves the same purpose as sizeof() in C, prevents memory management related errors from creeping in as we change types.
2) Value of uniformity of querying everything is that programmers will not go through the details of what is query-able and what is not and will attempt to query all attributes.
