### ISSUE TITLE
BB-15: Query components of monoids and semirings

### ISSUE THREAD

**Issue by mcmillan03** [GraphBLAS/graphblas-api-c#7]
`GxB_Monoid_operator()` return the monoid operator 
`GxB_Monoid_identity()`  return the monoid identity value

`GxB_Semiring_add()` return the additive monoid of a semiring 
`GxB_Semiring_multiply()`  return the binary operator of a semiring

**Comment by tgmattso** [comment]
I want introspection of all graphBLAS objects and Types.  So yes, I want this.

**Comment by manoj63** [comment]
To be consistent, you may also want the identity elements of the additive and multiplicative monoids of the semi-ring.

It may be useful to work out use cases where this capability is used to eliminate chances of errors under program edits, or creating of more concise code.
