### ISSUE TITLE
incorrect description of GrB_COMP_STRUCTURE in list of changes in appendices.tex

### ISSUE THREAD

**Issue by DrTimothyAldenDavis** [GraphBLAS/graphblas-api-c#80]
https://github.com/GraphBLAS/graphblas-api-c/blob/6692c3f7f85e73d12bcd70505571bbb4aa46b482/graph-api-c/appendices.tex#L20

GrB_COMP_STRUCTURE is not a descriptor.  It is a new value in the GrB_Desc_Value enum type.

**Comment by tgmattso** [comment]
OK.  Thank you for catching this.  Help me get the wording right.

This is what it currently says:

             \item We added a new built-in descriptor  {\sf GrB\_COMP\_STRUCTURE} and 
             an explicit reference to the default value of a descriptor field, {\sf GrB\_DEFAULT}.

How about this …

	We added new field values of type GrB\_Desc\_Value to use when working 
        with Descriptors, {\sf GrB\_COMP\_STRUCTURE}  and {\sf GrB\_DEFAULT}.


—Tim

**Comment by DrTimothyAldenDavis** [comment]
That revision looks great to me.
