### ISSUE TITLE
Release of v2.1 C API pdf

### ISSUE THREAD

**Issue by DrTimothyAldenDavis** [GraphBLAS/graphblas-api-c#81]
When will the v2.1 C API pdf be posted as an official release?  The main page of the github repo still shows the v2.0 C API pdf as the official release.

**Comment by DrTimothyAldenDavis** [comment]
I ask because I want to release GraphBLAS 9.0.0 very soon, and I want to include an exact copy of the released PDF.

**Comment by tgmattso** [comment]
I have placed a copy of the final 2.1 specification’s PDF on the www.graphblas.org <http://www.graphblas.org/> web site.   I have not announced the new spec yet on the graphBLAS forum mail list, but I will do so soon.

So go ahead and release graphBLAS 9.0.0

—Tim

**Comment by DrTimothyAldenDavis** [comment]
https://github.com/DrTimothyAldenDavis/GraphBLAS/releases/tag/v9.0.0.beta7

**Comment by DrTimothyAldenDavis** [comment]
See also a beta release of SuiteSparse 7.5.0 ( https://github.com/DrTimothyAldenDavis/SuiteSparse/releases/tag/v7.5.0.beta1 ) which contains GraphBLAS 9.0.0 (beta7) and the new stable LAGraph v1.1.0.

GraphBLAS 9.0.0.beta7 fully supports the new v2.1 C API.  LAGraph v1.1.0 can use GraphBLAS 7.x and later, since it doesn't use the new GrB get/set of the v2.1 C API.  LAGraph v1.2 (planned) will require the v2.1 C API and  v9.0.0 or later of SuiteSparse:GraphBLAS (if using that implementation).
